name: Deploy buy runner

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: debian-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: run tests
        run: python manage.py test
  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Stop and remove containers, networks
        run: docker compose down -v --remove-orphans
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker compose -f docker-compose.prod.yml up -d --build