name: Deploy buy runner

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: run tests
        run: python my_cv/manage.py test
  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: copy env secrets
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.prod
          echo "${{ secrets.ENV_LETSENCRYPT }}" > .env.letsencrypt
      - name: Stop and remove containers, networks
        run: docker compose -f docker-compose.prod.yml down -v --remove-orphans
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: copy env secrets
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.prod
          echo "${{ secrets.ENV_LETSENCRYPT }}" > .env.letsencrypt
      - name: docker-compose
        run: docker compose -f docker-compose.prod.yml up -d --build